module.exports=function(grunt){
    
    grunt.initConfig({
        pkg:grunt.file.readJSON('package.json'),
        uglify:{
            build:{
                src:['js_setup/Angular.js',
                    'js_setup/Angular-Route.js',
                    'ng_app/App.js',
                    'ng_app/common/AppService.js',
                    'ng_app/common/Constants.js',
                    'ng_app/common/Directives.js',
                    'ng_app/common/NavigationController.js',
                    'ng_app/common/Filters.js',
                    'ng_app/components/works/works.service.js',
                    'ng_app/components/works/works.controller.js',
                    'ng_app/components/works/works.module.js',
                    'ng_app/components/work_details/work_details.service.js',
                    'ng_app/components/work_details/work_details.controller.js',
                    'ng_app/components/work_details/work_details.module.js',    
                    'ng_app/components/about/about.service.js',
                    'ng_app/components/about/about.controller.js',
                    'ng_app/components/about/about.module.js'
                ],
                dest:'js/script.min.js'
            },
            dev:{
                options:{
                    beautify:true,
                    mangle:false,
                    compress:false,
                    preserveComments:'all'
                },
                src:['js_setup/Angular.js',
                    'js_setup/Angular-Route.js',
                    'ng_app/App.js',
                    'ng_app/common/AppService.js',
                    'ng_app/common/Constants.js',
                    'ng_app/common/Directives.js',
                    'ng_app/common/NavigationController.js',
                    'ng_app/common/Filters.js',
                    'ng_app/components/works/works.service.js',
                    'ng_app/components/works/works.controller.js',
                    'ng_app/components/works/works.module.js',
                    'ng_app/components/work_details/work_details.service.js',
                    'ng_app/components/work_details/work_details.controller.js',
                    'ng_app/components/work_details/work_details.module.js',    
                    'ng_app/components/about/about.service.js',
                    'ng_app/components/about/about.controller.js',
                    'ng_app/components/about/about.module.js'
                ],
                dest:'js/script.min.js'
            }
        },
        watch:{
            js:{
                files:['js_setup/Angular.js','js_setup/Angular-Route.js'],
                tasks:['uglify:dev']
            },
            css:{
                files:['css/scss/*.scss'],
                tasks:['sass:dev']
            }
        },
        sass:{
            dev:{
                options:{
                    outputStyle:'expanded'
                },
                files:{
                    'css/common.css':'css/scss/common.scss'
                }
            }
        }
    });
    
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-sass');

    grunt.registerTask('default',['uglify:dev','sass:dev']);
    grunt.registerTask('build',['uglify:build']);

};

